# codegen.toml

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces/core/wasmcloud-core.smithy"

[[models]]
# url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@cb504c8b7cfcee0a8c5ecdedf75757f4718ad4e6/core/wasmcloud-model.smithy"
path = "../../../interfaces/core"
files = [ "wasmcloud-model.smithy", "wasmcloud-common.smithy"  ]

[[models]]
path = "."
files = [ "union-demo.smithy", "smithy-types.smithy" ]

[rust]
output_dir = "rust"

[[rust.files]]
path = "src/union_demo.rs"
namespace = "org.wasmcloud.example.union_demo"

[[rust.files]]
path = "src/smithy_types.rs"
namespace = "org.wasmcloud.example.smithy_types"
