[package]
name = "blobby"
version = "0.2.1"
authors = [ "wasmCloud Team" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "blobby"

[dependencies]
form_urlencoded = "1.0"
futures = "0.3"
http = "0.2"
lazy_static = "1"
serde_json = "1.0.85"
tokio = { version = "1", features = ["parking_lot", "sync"] }
wasmbus-rpc = "0.13"
wasmcloud-interface-blobstore = "0.6"
wasmcloud-interface-httpserver = "0.10"
wasmcloud-interface-logging = "0.9"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
