# cargo-features = ["edition2021"]

[package]
name = "xkcd"
version = "0.1.1"
authors = [ "wasmcloud Team" ]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1"
console_log = "0.2"
futures = "0.3"
log = "0.4"
serde_bytes = "0.11"
serde_json ="1.0"
serde = {version = "1.0", features = ["derive"]}
wasmbus-rpc = "0.3"
wasmcloud-interface-httpserver = "0.1"
wasmcloud-interface-httpclient = { path="../../../interfaces/httpclient/rust" }
wasmcloud-interface-numbergen = "0.1"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
