[package]
name = "keyvalue"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wascc-codec = "0.3.4"
log = "0.4.8"
env_logger = "0.7.1"
prost = "0.5.0"